services:
  gateway:
    # image: gateway:latest
    build:
      context: .
      dockerfile: src/Gateway/Dockerfile
    ports:
      - "5000:8000"
    environment:
      - ASPNETCORE_URLS=http://+:8000

  earthquakes:
    # image: earthquakes:latest
    build:
      context: .
      dockerfile: src/EarthquakesMicroservice/Dockerfile
    ports:
      - "5001:8001"
    environment:
      - ASPNETCORE_URLS=http://+:8001
