apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: earthquakes
  name: earthquakes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: earthquakes
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: earthquakes
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: http://+:8001
          image: dmitryx/incidents-earthquakes:latest
          name: earthquakes
          ports:
            - containerPort: 8001
              protocol: TCP
      restartPolicy: Always
