apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: volcanoes
  name: volcanoes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: volcanoes
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: volcanoes
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: http://+:8002
          image: dmitryx/incidents-volcanoes:latest
          name: volcanoes
          ports:
            - containerPort: 8002
              protocol: TCP
      restartPolicy: Always
